.PHONY: clean
clean:
	rm -f *.res *.blk Ws_ftp.log *.txt *.log *.err *.disp *.grf *.meas *.por *.time *.rand *.par *.area *.grav *.replay block.in *.dat *.png *.html *.gnu *.fig *.spy1 *.spy2 *.cut *.m *~ geom.eps
