//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dda.rc
//
#define ICON_1                          1
#define ICON_DDAMAIN                    1
#define DDAAPMENU                       2
#define DDAAPACCEL                      3
#define ID_ANALYSIS_APPLY               3
#define MAIN_ABOUT                      11
#define MAIN_EXIT                       12
#define GEOM_NEW                        21
#define GEOM_BROWSE                     22
#define GEOM_EDITTXTD                   24
#define GEOM_VIEWGRF                    25
#define GEOM_APPLY                      26
#define GEOM_CANCEL                     27
#define GEOM_EDITTXTN                   28
#define GEOM_PGRF                       29
#define ANAL_NEW                        31
#define ANAL_BROWSE                     32
#define ANAL_EDITPARAMD                 33
#define ANAL_EDITBLX                    34
#define ANAL_RUN                        35
#define ANAL_PAUSE                      36
#define ANAL_ABORT                      37
#define ANAL_EDITPARAMN                 38
#define RES_VTXT                        41
#define HELP_GENINST                    41
#define RES_VGRF                        42
#define RES_PGRF                        44
#define DD_J1                           101
#define CD_LLX                          101
#define DD_J2                           102
#define CD_URX                          102
#define DD_J3                           103
#define CD_LLY                          103
#define IDI_ICON1                       103
#define DD_J4                           104
#define CD_URY                          104
#define DD_J5                           105
#define CD_ENJ                          105
#define IDI_ICON2                       105
#define ICON_DDA_ALT                    105
#define DD_J6                           106
#define CD_ENP                          106
#define DD_J7                           107
#define CD_GSP                          107
#define DD_J8                           108
#define CD_WINEXT                       108
#define DD_FP                           109
#define DD_MP                           110
#define DD_LP                           111
#define IDI_ICON0                       111
#define DD_HP                           112
#define DD_BOLT1                        113
#define DD_BOLTS                        114
#define DD_POINTS                       115
#define ICON_REDLEDON                   115
#define DD_JOINTS                       116
#define DD_X                            117
#define ICON_REDLEDOFF                  117
#define DD_Y                            118
#define ICON_GREENLEDOFF                118
#define IDC_GROUPBOX3                   119
#define ICON_GREENLEDON                 119
#define DD_GRON                         120
#define ICON_YELLLOWLEDOFF              120
#define DD_GROFF                        121
#define ICON_YELLOWLEDON                121
#define IDC_GROUPBOX4                   122
#define TOOLBAR_DDA_MAIN                122
#define DD_REMJ                         123
#define DD_REMP                         124
#define ICON_SWITCHOFF                  126
#define ICON_SWITCHON                   127
#define PROPSHEET                       129
#define IDB_BITMAP1                     131
#define IDR_HTML1                       132
#define IDB_BITMAP2                     140
#define IDB_BITMAP3                     142
#define IDR_MENU1                       145
#define ICON_ROCKBOLT                   153
#define ICON_EARTHQUAKE                 155
#define IDD_BOLTPROPERTIES              156
#define ICON_LOADPOINT                  157
#define IDD_SEISMIC                     158
#define ICON_CONTACT                    159
#define ICON_JOINTTYPE                  160
#define ICON_BLOCKMATERIALS             161
#define ICON_STOPWATCH                  162
#define IDD_TIMESTEP                    163
#define IDD_AFLAGS                      164
#define IDD_LOADPOINTS                  165
#define IDD_GRAVITY                     166
#define ICON_FLAGS                      167
#define ICON_GRAVITY                    168
#define IDD_CONTACT                     170
#define IDD_DIALOG1                     200
#define IDD_BLOCKPROPS                  200
#define IDD_DIALOG2                     201
#define IDD_JOINTPROPS                  201
#define MENU_HELPINDEX                  0x200
#define MENU_HELPHELP                   0x201
#define IDC_ENGLISH                     1000
#define IDC_METRIC                      1001
#define AD_ROTATION                     1003
#define AD_GRAVITY                      1004
#define IDC_OK                          1005
#define IDC_ORIG                        1007
#define AD_TDSCROLL                     1009
#define GD_BOLTNUMBER                   1011
#define GD_NUMBOLTS                     1012
#define IDC_EDIT1                       1013
#define IDC_MINX                        1013
#define APWEDGE_A1                      1013
#define IDC_DRAWSPACE                   1014
#define IDC_TMINX                       1015
#define IDC_MINY                        1017
#define IDC_MAXX                        1018
#define IDC_MAXY                        1019
#define IDC_TMINY                       1020
#define IDC_TMAXX                       1021
#define IDC_TMAXY                       1022
#define IDC_GRIDSP                      1023
#define IDC_GRID                        1024
#define APWEDGE_A2                      1025
#define APWEDGE_A3                      1026
#define APWEDGE_A4                      1027
#define APWEDGE_JF1                     1037
#define APWEDGE_JC1                     1038
#define APWEDGE_JT1                     1039
#define APWEDGE_JF2                     1040
#define APWEDGE_JC2                     1041
#define APWEDGE_JT2                     1042
#define APWEDGE_JF3                     1043
#define APWEDGE_JC3                     1044
#define APWEDGE_JT3                     1045
#define APWEDGE_SAVE                    1048
#define IDC_TAB1                        1049
#define IDC_TREE1                       1050
#define IDC_SLIDER1                     1051
#define IDC_SLIDER2                     1052
#define IDC_RADIO1                      1053
#define IDC_RADIO2                      1054
#define IDC_RADIO3                      1055
#define IDC_RADIO4                      1056
#define BPD_BOLTTYPE                    1057
#define IDC_EDIT2                       1058
#define IDC_EDIT3                       1059
#define IDC_BUTTON3                     1063
#define IDC_ADAPTIVE_TIME_STEP          1064
#define IDC_CHECK1                      1065
#define IDC_SHEARFORCETOL               1066
#define IDC_GRAVTIMESTEPS               1067
#define IDC_LOADRESIDUAL                1068
#define IDC_NORMALFORCETOL              1069
#define AD_DYNAMIC                      1070
#define AD_STATIC                       1071
#define IDC_LISTBOX3                    1102
#define GD_SAVE                         1102
#define GD_NJOI                         1103
#define GD_NFP                          1104
#define GD_NMP                          1105
#define GD_NLP                          1106
#define GD_NHP                          1107
#define GD_J1X1                         1110
#define GD_J1Y1                         1111
#define GD_J1X2                         1112
#define GD_J1Y2                         1113
#define GD_J1T                          1114
#define GD_J2X1                         1115
#define GD_J2Y1                         1116
#define GD_J2X2                         1117
#define GD_J2Y2                         1118
#define GD_J2T                          1119
#define GD_J3X1                         1120
#define GD_J3Y1                         1121
#define IDC_RADIOBUTTON1                1122
#define GD_J3X2                         1122
#define GD_J3Y2                         1123
#define GD_J3T                          1124
#define GD_J4X1                         1125
#define GD_J4Y1                         1126
#define GD_J4X2                         1127
#define GD_J4Y2                         1128
#define GD_J4T                          1129
#define GD_J5X1                         1130
#define GD_J5Y1                         1131
#define GD_J5X2                         1132
#define GD_J5Y2                         1133
#define GD_J5T                          1134
#define GD_P1X                          1137
#define GD_P1Y                          1138
#define GD_P1T                          1139
#define GD_P2X                          1140
#define GD_P2Y                          1141
#define GD_P2T                          1142
#define GD_P3X                          1143
#define GD_P3Y                          1144
#define GD_P3T                          1145
#define IDC_GROUPBOX1                   1146
#define IDC_GROUPBOX2                   1147
#define GD_JSCROLL                      1148
#define GD_PSCROLL                      1149
#define GD_JLAB1                        1150
#define GD_JLAB2                        1151
#define GD_JLAB3                        1152
#define GD_JLAB4                        1153
#define GD_JLAB5                        1154
#define GD_PLAB1                        1155
#define GD_PLAB2                        1156
#define GD_PLAB3                        1157
#define GD_BOLTX1                       1158
#define GD_BOLTY1                       1159
#define GD_BOLTX2                       1160
#define GD_BOLTY2                       1161
#define GD_BOLTSTIFFNESS                1162
#define GD_BOLTSTRENGTH                 1163
#define GD_BOLTPRETENSION               1164
#define GD_BOLTSCROLL                   1165
#define AD_SAVE                         1201
#define AD_STAT                         1202
#define AD_DYNAM                        1203
#define AD_NTS                          1204
#define AD_MAXDISP                      1205
#define AD_NJMAT                        1206
#define AD_JMAT                         1207
#define AD_FRIC                         1208
#define AD_COH                          1209
#define AD_TENS                         1210
#define AD_NBMAT                        1211
#define AD_BMAT                         1212
#define AD_DENS                         1213
#define AD_WT                           1214
#define AD_YMOD                         1215
#define AD_POIS                         1216
#define AD_ISSX                         1217
#define AD_ISSY                         1218
#define AD_ISSXY                        1219
#define AD_ISTX                         1220
#define AD_ISTY                         1221
#define AD_ISTXY                        1222
#define AD_IVELX                        1223
#define AD_IVELY                        1224
#define AD_IVELR                        1225
#define AD_JMINUS                       1226
#define AD_JPLUS                        1227
#define AD_BMINUS                       1228
#define AD_BPLUS                        1229
#define AD_ORIG                         1230
#define AD_SAVEINT                      1231
#define AD_FRIC3                        1232
#define AD_PSTRESS                      1233
#define AD_PSTRAIN                      1234
#define AD_FRIC4                        1235
#define AD_FRIC5                        1236
#define AD_TIMEDEPS                     1237
#define AD_STARTTIME1                   1238
#define AD_FORCEX1                      1239
#define AD_FORCEY1                      1240
#define AD_STARTTIME2                   1241
#define AD_FORCEX2                      1242
#define AD_FORCEY2                      1243
#define AD_STARTTIME3                   1244
#define AD_FORCEX3                      1245
#define AD_FORCEY3                      1246
#define AD_STARTTIME4                   1247
#define AD_FORCEX4                      1248
#define AD_FORCEY4                      1249
#define POPUP_GEOMETRY                  2000
#define POPUP_ANALYSIS                  2001
#define POPUP_REPLAY                    2002
#define ID_OPTION_DRAW                  32771
#define ID_OPTION_SELECT                32772
#define ID_OPTION_GRIDLINES             32773
#define ID_SETUP                        32774
#define ID_OPTION_SETUP                 32775
#define ID_FILE_NEW                     32776
#define TOOLBAR_NEW_GEOM                32776
#define ID_FILE_OPEN                    32777
#define ID_FILE_SAVE                    32778
#define ID_EDIT_DELETE                  32779
#define TOOLBAR_NEW_ANALYSIS            32779
#define RES_REPLAY                      40001
#define GEOM_VE                         40002
#define GEOM_EDIT_VE                    40003
#define ID_MENUITEM40004                40004
#define OPTIONS_ORIGGEOM                40004
#define ID_MENUITEM40005                40005
#define ID_MENUITEM40006                40006
#define ID_OPTIONS_XAXIS                40007
#define ID_OPTIONS_YAXIS                40008
#define ID_OPTIONS_BOTHAXES             40009
#define DEMO_TSLOPE                     40010
#define ID_GNUPLOT                      40011
#define DEMO_ARS                        40012
#define GEOMDRAW                        40013
#define APWEDGE                         40014
#define POPUP_ABORT                     40018
#define POPUP_EXIT                      40019
#define VIEW_TBAR                       40020
#define VIEW_SBAR                       40021
#define VIEW_POPUP                      40022
#define ICON_ABORT_ANALYSIS             40023
#define ID_BUTTON40024                  40024
#define ICON_GEOM_APPLY                 40025
#define VIEW_TOOLTIPS                   40026
#define ICON_PLUS                       40027
#define TOOLBAR_ZOOMIN                  40027
#define ICON_MINUS                      40028
#define TOOLBAR_ZOOMOUT                 40028
#define TOOLBAR_SWITCHOFF               40029
#define TOOLBAR_SWITCHON                40030
#define TOOLBAR_PRINT                   40031
#define ID_BUTTON40035                  40035
#define OPTIONS_SPYPLOTS                40036
#define ID_OPTIONS_FLAGSTATES           40037
#define OPTIONS_FLAGSTATES              40037
#define ID_OPTIONS_TIMING               40038
#define OPTIONS_TIMING                  40038
#define ID_OPTIONS_PARAMETERS           40039
#define OPTIONS_PARAMETERS              40039
#define DDAHELP_OVERVIEW                40040
#define DDAHELP_ANALYSIS                40041
#define DDAHELP_POSTPROCESS             40042
#define DDAHELP_ABOUTDDA                40043
#define DDAHELP_INDEX                   40044
#define DDAHELP_SEARCH                  40045
#define DDAHELP_GEOMETRY                40046
#define FILE_METAFILE                   40047
#define EXPORT_EMF                      40049
#define EXPORT_EPS                      40050
#define EXPORT_FIG                      40051
#define EXPORT_DXF                      40052
#define ID_POPUP_ITEM1                  40053
#define ID_POPUP_ITEM2                  40054
#define ID_POPUP_ITEM3                  40055
#define DDAHELP_TUTORIAL                40056
#define AD_TESTPROP                     40057
#define OPTIONS_FIXEDPOINTS             40059
#define OPTIONS_BLOCKAREAS              40060
#define OPTIONS_MEASUREDPOINTS          40061
#define ID_INDICATOR_MODE               59142
#define ID_INDICATOR_GRID               59143
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
